### ISSUE TITLE
project roadmap

### ISSUE THREAD

**Issue by gabeu** [Shyue/bubbles#2]
It felt weird to make multiple issues for obvious stuff but I'm gonna list stuff here:
- [x] 1: implement player
  - [ ] 1.1: make player move on both desktop and android
  - [x] 1.2: get a cool picture
- [x] 2: Make collisions work
  - [x] 2.1: bubble on bubble
  - [x] 2.2: bubble activation? maybe we spawn bubbles distributed across screen
  - [x] 2.3: player collision with bubbles
  - [ ] 2.4: bounce for both collision types this is technically separate
    - [ ] 2.4.1: how do bubble collisions even work? sticky collision? bouncy collision? something in between?
- [x] 3: flags
